backend:
  name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: master # Branch to update
  repo: needpower/identity # Repo for pushing new commits. Make sure to replace with your repo!

media_folder: static/assets
public_folder: assets

locale: "ru"

collections:
  - name: blog
    label: "Публикации"
    folder: "content"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата публикации", name: "date", widget: "datetime" }
      - {
          label: "Обложка",
          name: "cover",
          widget: "image",
          default: "",
          required: false,
        }
      - { label: "URL", name: "slug", widget: "string" }
      - { label: "Категория", name: "category", widget: "string" }
      - { label: "Основная мысль", name: "excerpt", widget: "string" }
      - { label: "Тело", name: "body", widget: "markdown" }

  - name: cupboard
    label: "Шкаф"
    folder: "cupboard"
    create: true
    slug: "{{slug}}.md"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Источник", name: "origin", widget: "string" }
      - { label: "О чём там?", name: "association", widget: "text" }
      - {
          label: "Категория",
          name: "category",
          widget: "list",
          allow_add: false,
        }
