backend:
  name: github
  branch: master
  repo: needpower/identity

media_folder: "static/assets"
public_folder: "/assets"

locale: "ru"

publish_mode: editorial_workflow

collections:
  - name: blog
    label: "Публикации"
    folder: "content"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    preview_path: notes/{{fields.slug}}
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата публикации", name: "date", widget: "datetime" }
      - { label: "Обложка", name: "cover", widget: "image", required: false }
      - { label: "URL", name: "slug", widget: "string" }
      - { label: "Категория", name: "category", widget: "string" }
      - { label: "Основная мысль", name: "excerpt", widget: "string" }
      - { label: "Тело", name: "body", widget: "markdown" }

  - name: cupboard
    label: "Шкаф"
    folder: "cupboard"
    create: true
    slug: "{{slug}}.md"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Источник", name: "origin", widget: "string" }
      - { label: "О чём там?", name: "association", widget: "text" }
      - {
          label: "Категория",
          name: "category",
          widget: "list",
          allow_add: false,
        }

  - name: projects
    label: "Проекты"
    folder: "projects"
    create: true
    slug: "{{slug}}.md"
    preview_path: projects/{{fields.slug}}
    fields:
      - {
          label: "Обложка",
          name: "cover",
          widget: "image",
          required: false,
          default: "/assets/venus.jpg",
        }
      - { label: "Название", name: "title", widget: "string" }
      - { label: "URL", name: "slug", widget: "string" }
      - { label: "Время создания", name: "timeframes", widget: "string" }
      - { label: "Результат", name: "result", widget: string }
      - {
          label: "Технологии",
          name: "technologies",
          widget: "list",
          field: { label: Название, name: "name", widget: "string" },
        }
      - { label: "Описание", name: "description", widget: "markdown" }
